{"name": "Проверка ошибки при авторизации с неверным логином или паролем", "status": "passed", "parameters": [{"name": "field", "value": "'login'"}], "start": 1713248402749, "stop": 1713248403014, "uuid": "7b7877d1-0f69-432b-b340-21d3264e86a1", "historyId": "6f03d551bed0deb02b29f981193e1d2e", "testCaseId": "4db5d0b446ab9c4f6b27d7c467c0f18e", "fullName": "tests.test_login#test_login_courier_with_invalid_log_or_pass", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "kekas"}, {"name": "thread", "value": "3496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}