{"name": "Проверка ошибки при авторизации с неверным логином или паролем", "status": "passed", "parameters": [{"name": "field", "value": "'password'"}], "start": 1713248403308, "stop": 1713248403585, "uuid": "8755bbc4-88de-4eb7-be7f-2acc0ef82580", "historyId": "ef4353ceb8d682b16af71b9c81b2e699", "testCaseId": "4db5d0b446ab9c4f6b27d7c467c0f18e", "fullName": "tests.test_login#test_login_courier_with_invalid_log_or_pass", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "kekas"}, {"name": "thread", "value": "3496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}